env:
  browser: true
  es6: true
plugins:
  - react
extends: airbnb

rules:
  camelcase: 1
  global-require: 0
  indent: 0
  import/no-unresolved:
    ignore: '**/*.ts(x)?'
  import/prefer-default-export: 0
  max-len: 0
  no-multi-spaces: 1
  no-return-assign: 0
  operator-linebreak: 0
  object-curly-newline: 0
  no-undef: 0
  no-unused-vars: 1
  padded-blocks: 0
  spaced-comment: 1
  template-curly-spacing: 0
  jsx-a11y/label-has-for: 0
  react/jsx-filename-extension: 0
  react/jsx-wrap-multilines: 0
  react/no-multi-comp: 0
  react/prefer-stateless-function: 1
  react/prop-types: 1
  react/react-in-jsx-scope: 0
  react/button-has-type: 0


# env:
#   browser: true
#   es6: true
# globals:
#   Atomics: readonly
#   SharedArrayBuffer: readonly
# parserOptions:
#   ecmaFeatures:
#     jsx: true
#   ecmaVersion: 2018
#   sourceType: module
# plugins:
#   - react
# rules: {}
